services:
  - type: web
    name: learnify-server
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      # Add your other environment variables here 